server {
    listen       80;
    server_name  localhost;

    charset utf-8;
    root   /usr/share/nginx/html;
    index  index.html;

    # Todas las rutas deben redirigirse a index.html para que React Router maneje el enrutamiento
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Configuraciones de caché para contenido estático (opcional pero recomendado)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    # Redireccionar errores de servidor al html estático de error por defecto de nginx
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
